# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2022-02-27
openapi: "3.1.0"
info:
  title: "my api"
  version: "1.0"

paths:
  "/rest-api":
    get:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        200:
          description: A response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name: { "type": string }
